default: &default
  adapter: postgresql
  encoding: unicode
  # port: 5432
  # username: <%= ENV['DB_USERNAME'] %>
  # host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pati_pati_development

test:
  <<: *default
  database: pati_pati_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASSWD'] %>
